# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vaishnavi Hire
email: hire.v@husky.neu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: VaishnaviHire
github_username:  VaishnaviHire

author:
  name: Vaishnavi Hire
  picture: assets/images/profile.jpg
# Build settings
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins:
  - jekyll-feed


paginate: 5  # amount of posts to show per page
paginate_path: /page:num/
search: true

collections:
  recipes:
    output: true
    permalink: /:collection/:path/

defaults:
# _posts
- scope:
    path: "_posts"
    type: posts
  values:
    layout: post
    read_time: true
# _recipes
- scope:
    path: "_recipes"
    type: recipes
  values:
    layout: post
    read_time: true

## Sass/SCSS
#sass:
#  sass_dir: _sass
#  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Exclude from processingremote_theme: "mmistakes/jekyll-theme-basically-basic".
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
